theme: just-the-docs
plugins:
  - jekyll-seo-tag
  - jekyll-default-layout

callouts:
  note:
    title: ğŸ“ Note
    color: blue
  warning:
    title: âš ï¸ Warning
    color: red
  highlight:
    color: yellow
  notice:
    title: âœ… Notice
    color: yellow
  info:
    title: ğŸ’¡ Info
    color: yellow
  save:
    title: ğŸ’¾
    color: yellow
  activity:
    color: grey-lt
  
    
callouts_level: quiet    
callouts_opacity: 0.2    