theme: just-the-docs
plugins:
  - jekyll-seo-tag
  - jekyll-default-layout

callouts:
  note:
    title: Note
    color: blue
  warning:
    title: âš ï¸ Warning
    color: red
  tip:
    title: ğŸ’¡ Tip
    color: gree