title: ğŸ§¬ MEB Training Suite
description: Bookmark this to keep an eye on my project updates!

url: https://gamalielcabria.github.io/

plugins:
  - jekyll-remote-theme

remote_theme: just-the-docs/just-the-docs

aux_links:
  Template Repository: https://github.com/gamalielcabria

search_enabled: true

callouts:
  note:
    title: ğŸ“ Note
    color: blue
  warning:
    title: âš ï¸ Warning
    color: red
  highlight:
    color: yellow
  notice:
    title: âœ… Notice
    color: yellow
  info:
    title: ğŸ’¡ Info
    color: yellow
  save:
    title: ğŸ’¾
    color: yellow
  activity:
    color: grey-lt
  
    
callouts_level: quiet    
callouts_opacity: 0.2      